version: "3.9"

services:
  neo4j:
    image: neo4j:latest
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - neo4j_data:/data/
    environment:
      - NEO4J_AUTH=none
  mq:
    image: rabbitmq:3-management-alpine
    hostname: mq
    ports:
      - 15672:15672
  stream-handler:
    build:
      context: ./services/stream-handler
      dockerfile: Dockerfile
    depends_on:
      - mq
    volumes:
      - ./services/stream-handler:/usr/src/app
      - /usr/src/app/node_modules
    command: ["./wait-for-it.sh", "mq:5672", "--", "npm", "start"]
  mq-worker:
    build:
      context: ./services/mq-worker
      dockerfile: Dockerfile
    depends_on:
      - mq
    volumes:
      - ./services/mq-worker:/usr/src/app
      - /usr/src/app/node_modules
    command: ["./wait-for-it.sh", "mq:5672", "--", "npm", "start"]
  api:
    build:
      context: ./services/api
      dockerfile: Dockerfile
    depends_on:
      - neo4j
    ports:
      - "5000:5000"
    volumes:
      - ./services/api:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    command: ["./wait-for-it.sh", "neo4j:7687", "--", "npm", "start"]
  client:
    build:
      context: ./services/client
      dockerfile: Dockerfile
    volumes:
      - ./services/client:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
volumes:
  neo4j_data:
