version: "3.6"

services:
  neo4j:
    image: neo4j:latest
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=none
  mq:
    image: rabbitmq:3-management-alpine
    hostname: mq
    ports:
      - 15672:15672
  stream-handler:
    build:
      context: ./services/stream-handler
      dockerfile: Dockerfile
    depends_on:
      - mq
    command: ["./wait-for-it.sh", "mq:5672", "--", "npm", "start"]
  mq-worker:
    build:
      context: ./services/mq-worker
      dockerfile: Dockerfile
    depends_on:
      - mq
    command: ["./wait-for-it.sh", "mq:5672", "--", "npm", "start"]
