version: "3.6"

services:
  neo:
    image: neo4j:latest
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - neo4j_data:/data/
    environment:
      - NEO4J_AUTH=none
  mq:
    image: rabbitmq:3-management-alpine
    hostname: mq
    ports:
      - 15672:15672
  stream-handler:
    build:
      context: ./stream-handler
      dockerfile: Dockerfile
    depends_on:
      - mq
    command: ["./wait-for-it.sh", "mq:5672", "--", "npm", "start"]
volumes:
  neo4j_data:
